enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm-v7a"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm-v7a"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"




# https://github.com/j-hc/revanced-magisk-module/issues/554
[Music-Extended]
enabled = false
app-name = "Music"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"

[YouTube-Extended]
enabled = false
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

